//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int ID_Configuracion { get; set; }
        public int TrabajaConPlantaAlta { get; set; }
        public int AvisoEspera { get; set; }
        public int TiempoFormAbierto { get; set; }
    }
}
