//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int ID_Detalle { get; set; }
        public int ID_Pedido { get; set; }
        public int ID_Articulo { get; set; }
        public Nullable<int> ID_Chef { get; set; }
        public int Cantidad { get; set; }
        public string Nota { get; set; }
        public Nullable<double> Precio { get; set; }
        public int ID_EstadoDetalle { get; set; }
        public int CantidadAgregada { get; set; }
        public int ID_ArticuloEntregado { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual ArticuloEntregado ArticuloEntregado { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual EstadoDetalle EstadoDetalle { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
