//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionRestaurante
    {
        public int ID_InformacionRestaurante { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Eslogan { get; set; }
        public long TelefonoUno { get; set; }
        public Nullable<long> TelefonoDos { get; set; }
    }
}
