//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mesa()
        {
            this.MesaXReserva = new HashSet<MesaXReserva>();
            this.PedidoXMesa = new HashSet<PedidoXMesa>();
        }
    
        public int ID_Mesa { get; set; }
        public int Numero { get; set; }
        public int ID_EstadoMesa { get; set; }
        public int Capacidad { get; set; }
        public int ID_Usuario { get; set; }
    
        public virtual EstadoMesa EstadoMesa { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesaXReserva> MesaXReserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoXMesa> PedidoXMesa { get; set; }
    }
}
