//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDRestauranteEntities : DbContext
    {
        public BDRestauranteEntities()
            : base("name=BDRestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<ArticuloEntregado> ArticuloEntregado { get; set; }
        public virtual DbSet<BlockDeNota> BlockDeNota { get; set; }
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<CategoriaArticulo> CategoriaArticulo { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<Detalle> Detalle { get; set; }
        public virtual DbSet<EstadoArticulo> EstadoArticulo { get; set; }
        public virtual DbSet<EstadoCaja> EstadoCaja { get; set; }
        public virtual DbSet<EstadoCategoriaArticulo> EstadoCategoriaArticulo { get; set; }
        public virtual DbSet<EstadoDelivery> EstadoDelivery { get; set; }
        public virtual DbSet<EstadoDetalle> EstadoDetalle { get; set; }
        public virtual DbSet<EstadoMesa> EstadoMesa { get; set; }
        public virtual DbSet<EstadoPedido> EstadoPedido { get; set; }
        public virtual DbSet<EstadoReserva> EstadoReserva { get; set; }
        public virtual DbSet<EstadoUsuario> EstadoUsuario { get; set; }
        public virtual DbSet<InformacionRestaurante> InformacionRestaurante { get; set; }
        public virtual DbSet<Mesa> Mesa { get; set; }
        public virtual DbSet<MesaXReserva> MesaXReserva { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<PedidoXMesa> PedidoXMesa { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<TipoDeMonto> TipoDeMonto { get; set; }
        public virtual DbSet<TipoDeMovimiento> TipoDeMovimiento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<VencimientoFuncionalidades> VencimientoFuncionalidades { get; set; }
        public virtual DbSet<ViaDeContacto> ViaDeContacto { get; set; }
        public virtual DbSet<ClienteXPedido> ClienteXPedido { get; set; }
        public virtual DbSet<EstadoClienteXPedido> EstadoClienteXPedido { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosMasVendidosCarta_Result> SP_ArticulosMasVendidosCarta(string p_FechaDesde, string p_FechaHasta, Nullable<int> p_ParaCocina)
        {
            var p_FechaDesdeParameter = p_FechaDesde != null ?
                new ObjectParameter("p_FechaDesde", p_FechaDesde) :
                new ObjectParameter("p_FechaDesde", typeof(string));
    
            var p_FechaHastaParameter = p_FechaHasta != null ?
                new ObjectParameter("p_FechaHasta", p_FechaHasta) :
                new ObjectParameter("p_FechaHasta", typeof(string));
    
            var p_ParaCocinaParameter = p_ParaCocina.HasValue ?
                new ObjectParameter("p_ParaCocina", p_ParaCocina) :
                new ObjectParameter("p_ParaCocina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosMasVendidosCarta_Result>("SP_ArticulosMasVendidosCarta", p_FechaDesdeParameter, p_FechaHastaParameter, p_ParaCocinaParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosMasVendidosCategoriaCarta_Result> SP_ArticulosMasVendidosCategoriaCarta(string p_FechaDesde, string p_FechaHasta)
        {
            var p_FechaDesdeParameter = p_FechaDesde != null ?
                new ObjectParameter("p_FechaDesde", p_FechaDesde) :
                new ObjectParameter("p_FechaDesde", typeof(string));
    
            var p_FechaHastaParameter = p_FechaHasta != null ?
                new ObjectParameter("p_FechaHasta", p_FechaHasta) :
                new ObjectParameter("p_FechaHasta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosMasVendidosCategoriaCarta_Result>("SP_ArticulosMasVendidosCategoriaCarta", p_FechaDesdeParameter, p_FechaHastaParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosMasVendidosCategoriaDelivery_Result> SP_ArticulosMasVendidosCategoriaDelivery(string p_FechaDesde, string p_FechaHasta)
        {
            var p_FechaDesdeParameter = p_FechaDesde != null ?
                new ObjectParameter("p_FechaDesde", p_FechaDesde) :
                new ObjectParameter("p_FechaDesde", typeof(string));
    
            var p_FechaHastaParameter = p_FechaHasta != null ?
                new ObjectParameter("p_FechaHasta", p_FechaHasta) :
                new ObjectParameter("p_FechaHasta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosMasVendidosCategoriaDelivery_Result>("SP_ArticulosMasVendidosCategoriaDelivery", p_FechaDesdeParameter, p_FechaHastaParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosMasVendidosCategoriaReserva_Result> SP_ArticulosMasVendidosCategoriaReserva(string p_FechaDesde, string p_FechaHasta)
        {
            var p_FechaDesdeParameter = p_FechaDesde != null ?
                new ObjectParameter("p_FechaDesde", p_FechaDesde) :
                new ObjectParameter("p_FechaDesde", typeof(string));
    
            var p_FechaHastaParameter = p_FechaHasta != null ?
                new ObjectParameter("p_FechaHasta", p_FechaHasta) :
                new ObjectParameter("p_FechaHasta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosMasVendidosCategoriaReserva_Result>("SP_ArticulosMasVendidosCategoriaReserva", p_FechaDesdeParameter, p_FechaHastaParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosMasVendidosDelivery_Result> SP_ArticulosMasVendidosDelivery(string p_FechaDesde, string p_FechaHasta, Nullable<int> p_ParaCocina)
        {
            var p_FechaDesdeParameter = p_FechaDesde != null ?
                new ObjectParameter("p_FechaDesde", p_FechaDesde) :
                new ObjectParameter("p_FechaDesde", typeof(string));
    
            var p_FechaHastaParameter = p_FechaHasta != null ?
                new ObjectParameter("p_FechaHasta", p_FechaHasta) :
                new ObjectParameter("p_FechaHasta", typeof(string));
    
            var p_ParaCocinaParameter = p_ParaCocina.HasValue ?
                new ObjectParameter("p_ParaCocina", p_ParaCocina) :
                new ObjectParameter("p_ParaCocina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosMasVendidosDelivery_Result>("SP_ArticulosMasVendidosDelivery", p_FechaDesdeParameter, p_FechaHastaParameter, p_ParaCocinaParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosMasVendidosReserva_Result> SP_ArticulosMasVendidosReserva(string p_FechaDesde, string p_FechaHasta, Nullable<int> p_ParaCocina)
        {
            var p_FechaDesdeParameter = p_FechaDesde != null ?
                new ObjectParameter("p_FechaDesde", p_FechaDesde) :
                new ObjectParameter("p_FechaDesde", typeof(string));
    
            var p_FechaHastaParameter = p_FechaHasta != null ?
                new ObjectParameter("p_FechaHasta", p_FechaHasta) :
                new ObjectParameter("p_FechaHasta", typeof(string));
    
            var p_ParaCocinaParameter = p_ParaCocina.HasValue ?
                new ObjectParameter("p_ParaCocina", p_ParaCocina) :
                new ObjectParameter("p_ParaCocina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosMasVendidosReserva_Result>("SP_ArticulosMasVendidosReserva", p_FechaDesdeParameter, p_FechaHastaParameter, p_ParaCocinaParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosMenosVendidosCarta_Result> SP_ArticulosMenosVendidosCarta(string p_FechaDesde, string p_FechaHasta, Nullable<int> p_ParaCocina)
        {
            var p_FechaDesdeParameter = p_FechaDesde != null ?
                new ObjectParameter("p_FechaDesde", p_FechaDesde) :
                new ObjectParameter("p_FechaDesde", typeof(string));
    
            var p_FechaHastaParameter = p_FechaHasta != null ?
                new ObjectParameter("p_FechaHasta", p_FechaHasta) :
                new ObjectParameter("p_FechaHasta", typeof(string));
    
            var p_ParaCocinaParameter = p_ParaCocina.HasValue ?
                new ObjectParameter("p_ParaCocina", p_ParaCocina) :
                new ObjectParameter("p_ParaCocina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosMenosVendidosCarta_Result>("SP_ArticulosMenosVendidosCarta", p_FechaDesdeParameter, p_FechaHastaParameter, p_ParaCocinaParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosMenosVendidosCategoriaCarta_Result> SP_ArticulosMenosVendidosCategoriaCarta(string p_FechaDesde, string p_FechaHasta)
        {
            var p_FechaDesdeParameter = p_FechaDesde != null ?
                new ObjectParameter("p_FechaDesde", p_FechaDesde) :
                new ObjectParameter("p_FechaDesde", typeof(string));
    
            var p_FechaHastaParameter = p_FechaHasta != null ?
                new ObjectParameter("p_FechaHasta", p_FechaHasta) :
                new ObjectParameter("p_FechaHasta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosMenosVendidosCategoriaCarta_Result>("SP_ArticulosMenosVendidosCategoriaCarta", p_FechaDesdeParameter, p_FechaHastaParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosMenosVendidosCategoriaDelivery_Result> SP_ArticulosMenosVendidosCategoriaDelivery(string p_FechaDesde, string p_FechaHasta)
        {
            var p_FechaDesdeParameter = p_FechaDesde != null ?
                new ObjectParameter("p_FechaDesde", p_FechaDesde) :
                new ObjectParameter("p_FechaDesde", typeof(string));
    
            var p_FechaHastaParameter = p_FechaHasta != null ?
                new ObjectParameter("p_FechaHasta", p_FechaHasta) :
                new ObjectParameter("p_FechaHasta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosMenosVendidosCategoriaDelivery_Result>("SP_ArticulosMenosVendidosCategoriaDelivery", p_FechaDesdeParameter, p_FechaHastaParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosMenosVendidosCategoriaReserva_Result> SP_ArticulosMenosVendidosCategoriaReserva(string p_FechaDesde, string p_FechaHasta)
        {
            var p_FechaDesdeParameter = p_FechaDesde != null ?
                new ObjectParameter("p_FechaDesde", p_FechaDesde) :
                new ObjectParameter("p_FechaDesde", typeof(string));
    
            var p_FechaHastaParameter = p_FechaHasta != null ?
                new ObjectParameter("p_FechaHasta", p_FechaHasta) :
                new ObjectParameter("p_FechaHasta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosMenosVendidosCategoriaReserva_Result>("SP_ArticulosMenosVendidosCategoriaReserva", p_FechaDesdeParameter, p_FechaHastaParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosMenosVendidosDelivery_Result> SP_ArticulosMenosVendidosDelivery(string p_FechaDesde, string p_FechaHasta, Nullable<int> p_ParaCocina)
        {
            var p_FechaDesdeParameter = p_FechaDesde != null ?
                new ObjectParameter("p_FechaDesde", p_FechaDesde) :
                new ObjectParameter("p_FechaDesde", typeof(string));
    
            var p_FechaHastaParameter = p_FechaHasta != null ?
                new ObjectParameter("p_FechaHasta", p_FechaHasta) :
                new ObjectParameter("p_FechaHasta", typeof(string));
    
            var p_ParaCocinaParameter = p_ParaCocina.HasValue ?
                new ObjectParameter("p_ParaCocina", p_ParaCocina) :
                new ObjectParameter("p_ParaCocina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosMenosVendidosDelivery_Result>("SP_ArticulosMenosVendidosDelivery", p_FechaDesdeParameter, p_FechaHastaParameter, p_ParaCocinaParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosMenosVendidosReserva_Result> SP_ArticulosMenosVendidosReserva(string p_FechaDesde, string p_FechaHasta, Nullable<int> p_ParaCocina)
        {
            var p_FechaDesdeParameter = p_FechaDesde != null ?
                new ObjectParameter("p_FechaDesde", p_FechaDesde) :
                new ObjectParameter("p_FechaDesde", typeof(string));
    
            var p_FechaHastaParameter = p_FechaHasta != null ?
                new ObjectParameter("p_FechaHasta", p_FechaHasta) :
                new ObjectParameter("p_FechaHasta", typeof(string));
    
            var p_ParaCocinaParameter = p_ParaCocina.HasValue ?
                new ObjectParameter("p_ParaCocina", p_ParaCocina) :
                new ObjectParameter("p_ParaCocina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosMenosVendidosReserva_Result>("SP_ArticulosMenosVendidosReserva", p_FechaDesdeParameter, p_FechaHastaParameter, p_ParaCocinaParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosVendidosPorMesCarta_Result> SP_ArticulosVendidosPorMesCarta(Nullable<int> p_Año)
        {
            var p_AñoParameter = p_Año.HasValue ?
                new ObjectParameter("p_Año", p_Año) :
                new ObjectParameter("p_Año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosVendidosPorMesCarta_Result>("SP_ArticulosVendidosPorMesCarta", p_AñoParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosVendidosPorMesDelivery_Result> SP_ArticulosVendidosPorMesDelivery(Nullable<int> p_Año)
        {
            var p_AñoParameter = p_Año.HasValue ?
                new ObjectParameter("p_Año", p_Año) :
                new ObjectParameter("p_Año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosVendidosPorMesDelivery_Result>("SP_ArticulosVendidosPorMesDelivery", p_AñoParameter);
        }
    
        public virtual ObjectResult<SP_ArticulosVendidosPorMesReserva_Result> SP_ArticulosVendidosPorMesReserva(Nullable<int> p_Año)
        {
            var p_AñoParameter = p_Año.HasValue ?
                new ObjectParameter("p_Año", p_Año) :
                new ObjectParameter("p_Año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ArticulosVendidosPorMesReserva_Result>("SP_ArticulosVendidosPorMesReserva", p_AñoParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_GananciasYPerdidasPorMes_Result> SP_GananciasYPerdidasPorMes(Nullable<int> p_Año)
        {
            var p_AñoParameter = p_Año.HasValue ?
                new ObjectParameter("p_Año", p_Año) :
                new ObjectParameter("p_Año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GananciasYPerdidasPorMes_Result>("SP_GananciasYPerdidasPorMes", p_AñoParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SP_VentasPorMozoPorMes_Result> SP_VentasPorMozoPorMes(Nullable<int> p_Año)
        {
            var p_AñoParameter = p_Año.HasValue ?
                new ObjectParameter("p_Año", p_Año) :
                new ObjectParameter("p_Año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VentasPorMozoPorMes_Result>("SP_VentasPorMozoPorMes", p_AñoParameter);
        }
    }
}
