//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VencimientoFuncionalidades
    {
        public int ID_VencimientoFuncionalidades { get; set; }
        public System.DateTime VencimientoGeneral { get; set; }
        public System.DateTime VencimientoFunciones { get; set; }
    }
}
